services:
  - type: web
    name: book-management-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 